// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace RazorSiteML.ConsoleApp
{
    internal class CustomVisionTrainingClient
    {
        public object ApiKey { get; internal set; }
        public object Endpoint { get; internal set; }

        internal object CreateProject(string v)
        {
            throw new NotImplementedException();
        }
    }
}